"""Domain models package for M0 academic schema."""

from app.models.base import DomainModel
from app.models.domain import (
    AcademicSessionModel,
    AcademicSettingsModel,
    AssignmentModel,
    AssignmentSubmissionModel,
    AttendanceRecordModel,
    AttendanceSessionModel,
    CourseModel,
    EventModel,
    ExamRuleModel,
    FinalMarkModel,
    GradeRuleModel,
    GradeRuleSetModel,
    GradingSystemModel,
    MarkModel,
    NoticeModel,
    PromotionAuditEventModel,
    PromotionModel,
    RoutineModel,
    SyllabusModel,
    SchoolClassModel,
    SchoolExamModel,
    SectionModel,
    SemesterModel,
    StudentEnrollmentModel,
    TeacherAssignmentModel,
)

__all__ = [
    "DomainModel",
    "AcademicSessionModel",
    "AcademicSettingsModel",
    "AssignmentModel",
    "AssignmentSubmissionModel",
    "AttendanceRecordModel",
    "AttendanceSessionModel",
    "CourseModel",
    "EventModel",
    "ExamRuleModel",
    "FinalMarkModel",
    "GradeRuleModel",
    "GradeRuleSetModel",
    "GradingSystemModel",
    "MarkModel",
    "NoticeModel",
    "PromotionAuditEventModel",
    "PromotionModel",
    "RoutineModel",
    "SyllabusModel",
    "SchoolClassModel",
    "SchoolExamModel",
    "SectionModel",
    "SemesterModel",
    "StudentEnrollmentModel",
    "TeacherAssignmentModel",
]
